### ISSUE TITLE
使用最新版本（第12个）时遇到的问题

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#11]
![Screenshot_20241002_123413_com example masiro](https://github.com/user-attachments/assets/6bf8fbe4-7a96-4a24-b335-5d3e3d4a008e)
![Screenshot_20241002_123416_com example masiro](https://github.com/user-attachments/assets/e784c643-842f-4d86-95d9-c40b9a629108)

https://github.com/user-attachments/assets/6883bdc7-e63c-4c78-8297-1744335412ac

![Screenshot_20241002_123259](https://github.com/user-attachments/assets/d227eb71-2410-46fa-87be-de712a1e3088)
这次更新我把它装到了aosp12的设备上，在登陆完账号后收藏页有错误代码，设置页账号信息加载不出来，需要虫重新进入软件才可以。然后收藏里卡片的简介处，部分书有出现代码的情况（是html代码）

**Comment by Qing-Novel** [comment]
ps：刚发现多任务中心里软件没有名字，希望后续
![Screenshot_20241002_123938_com huawei android launcher](https://github.com/user-attachments/assets/5c99d3c9-2210-40a3-b090-f02c731ffcf9)
可以加一下

**Comment by qixiaoo** [comment]
收藏页加载不出来的问题我上午也遇到了，原因是 http 接口返回的数据变了。上午尝试修复了一版后，在我这边看起来貌似是没问题了，不过看起来在你那边还有问题。这个不太好复现，可能我需要再观察下。

简介处的 html 代码是 http 接口返回的 json 数据内包含的，这里我没做特殊处理，目前就先这样吧，或许后面可以考虑引入渲染 html 代码的第三方依赖。

多任务中心里软件没有名字的问题我这边也有，应该也好加，我修复一下。

**Comment by Qing-Novel** [comment]
> 收藏页加载不出来的问题我上午也遇到了，原因是 http 接口返回的数据变了。上午尝试修复了一版后，在我这边看起来貌似是没问题了，不过看起来在你那边还有问题。这个不太好复现，可能我需要再观察下。
> 
> 简介处的 html 代码是 http 接口返回的 json 数据内包含的，这里我没做特殊处理，目前就先这样吧，或许后面可以考虑引入渲染 html 代码的第三方依赖。
> 
> 多任务中心里软件没有名字的问题我这边也有，应该也好加，我修复一下。

好的好的，麻烦佬了

**Comment by qixiaoo** [comment]
> 收藏页加载不出来的问题我上午也遇到了，原因是 http 接口返回的数据变了。上午尝试修复了一版后，在我这边看起来貌似是没问题了，不过看起来在你那边还有问题。这个不太好复现，可能我需要再观察下。
> 
> 简介处的 html 代码是 http 接口返回的 json 数据内包含的，这里我没做特殊处理，目前就先这样吧，或许后面可以考虑引入渲染 html 代码的第三方依赖。
> 
> 多任务中心里软件没有名字的问题我这边也有，应该也好加，我修复一下。

问题一看起来是重新安装后没有登录信息，此时请求接口会拿不到数据，从而导致问题。
已通过延迟请求接口修复该问题。
