### ISSUE TITLE
关于开屏页状态栏黑色的建议

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#17]
![Videoframe_20241005_115439_com huawei photos](https://github.com/user-attachments/assets/d28d4cdd-1247-48dd-ab55-91c8913fb908)

https://github.com/user-attachments/assets/3f65691e-170b-4bc0-a4cb-9fe763d5e00a

发现这个问题也有段时间了，希望佬能改下，让状态栏跟下方的页面一个颜色

**Comment by qixiaoo** [comment]
看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。

**Comment by Qing-Novel** [comment]
> 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。

我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？

**Comment by Qing-Novel** [comment]
> > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> 
> 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？

展示图标这个，我之前下的漫游x版b站也是展示图标作为启动页

**Comment by qixiaoo** [comment]
> > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> 
> 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？

不太确定，我 Google 下有没有类似的问题。

**Comment by Qing-Novel** [comment]
> > > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> > 
> > 
> > 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？
> 
> 不太确定，我 Google 下有没有类似的问题。

好的好的辛苦大佬了

**Comment by Qing-Novel** [comment]
> > > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> > 
> > 
> > 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？
> 
> 不太确定，我 Google 下有没有类似的问题。

佬可以参考下FIClash这个软件

https://github.com/user-attachments/assets/674d3eca-dc38-4fe2-a126-4f8833ac3126

**Comment by Qing-Novel** [comment]
> > > > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> > > 
> > > 
> > > 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？
> > 
> > 
> > 不太确定，我 Google 下有没有类似的问题。
> 
> 佬可以参考下FIClash这个软件
> 
>  SVID_20241008_114722_1.mp4

FlClash也是flutter做的，佬可以参考下这个软件是如何处理状态栏的问题，这个软件就没有状态栏黑色的问题：https://github.com/chen08209/FlClash

**Comment by qixiaoo** [comment]
> > > > > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> > > > 
> > > > 
> > > > 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？
> > > 
> > > 
> > > 不太确定，我 Google 下有没有类似的问题。
> > 
> > 
> > 佬可以参考下FIClash这个软件
> > SVID_20241008_114722_1.mp4
> 
> FlClash也是flutter做的，佬可以参考下这个软件是如何处理状态栏的问题，这个软件就没有状态栏黑色的问题：https://github.com/chen08209/FlClash

我研究研究。

**Comment by Qing-Novel** [comment]
> > > > > > 看起来在不同的 Android 版本上表现不太一样。我的 Android 9 默认是全黑展开，Android 14 则是会展示图标作为启动过渡页。
> > > > > 
> > > > > 
> > > > > 我这边是aosp10（鸿蒙2）和aosp12（鸿蒙4.2），佬看看能否优化下？
> > > > 
> > > > 
> > > > 不太确定，我 Google 下有没有类似的问题。
> > > 
> > > 
> > > 佬可以参考下FIClash这个软件
> > > SVID_20241008_114722_1.mp4
> > 
> > 
> > FlClash也是flutter做的，佬可以参考下这个软件是如何处理状态栏的问题，这个软件就没有状态栏黑色的问题：https://github.com/chen08209/FlClash
> 
> 我研究研究。

麻烦佬了

**Comment by Qing-Novel** [comment]
看到佬对这个做了优化，不过想问下佬目前状态栏的这个灰色透明背景是佬这样设计的吗？要是是这样设计的话那这个问题应该可以认为是修复了
![2024_10_13_155728236](https://github.com/user-attachments/assets/13245ae0-874b-4a3f-a507-99819d7be519)

https://github.com/user-attachments/assets/0cfce939-107d-4e5c-99cd-ca1ef63892fc


Uploading petal_20241013_155929.mp4…

**Comment by qixiaoo** [comment]
我慢放你上面的视频看起来是修复了，没有状态栏的黑条了。
至于后面的灰色状态栏看起来是页面正常展示后的效果，上面本身的状态栏没有隐藏。

**Comment by qixiaoo** [comment]
![image](https://github.com/user-attachments/assets/32ef64f2-3a61-4b08-8e55-455ecf5abaaa)

**Comment by Qing-Novel** [comment]
> 我慢放你上面的视频看起来是修复了，没有状态栏的黑条了。 至于后面的灰色状态栏看起来是页面正常展示后的效果，上面本身的状态栏没有隐藏。

好的。那想问下，呃，其实我个人觉得这个灰色状态栏直接使用背景色会更好看点。。。虽然现在比黑色状态栏顺眼很多了。。。
