### ISSUE TITLE
关于灰色状态栏的问题

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#20]
灰色状态栏在打开关于界面后会消失，之后不再显示（重启软件才会显示）
佬，我是觉得状态栏直接跟随下方页面背景色更好看点的

https://github.com/user-attachments/assets/6456c0d8-5358-4588-aea5-2e6d3cf04a68

**Comment by qixiaoo** [comment]
确实诶，应该可以改成背景色，我看看

**Comment by Qing-Novel** [comment]
> 确实诶，应该可以改成背景色，我看看

麻烦佬了
