### ISSUE TITLE
一个请求

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#22]
请问佬未来能给深夜读书会做个app吗？
网站：http://ritdon.com/forum.php?forumlist=1&mobile=no
这个跟真白萌一样，是个轻小说论坛，不过多发资源，在线阅读少
![Screenshot_20241016_175148_com huawei browser](https://github.com/user-attachments/assets/47fe8e34-14d5-4aa0-8964-d8f2a5ffbeb9)

**Comment by qixiaoo** [comment]
我短期内应该不会开新项目了，最近要疯狂摸鱼了。

**Comment by qixiaoo** [comment]
或许可以问问别的大佬。

**Comment by Qing-Novel** [comment]
> 我短期内应该不会开新项目了，最近要疯狂摸鱼了。

好的好的

**Comment by Qing-Novel** [comment]
> 或许可以问问别的大佬。

问过一位了，那位不用就没接🤣

**Comment by qixiaoo** [comment]
> > 或许可以问问别的大佬。
> 
> 问过一位了，那位不用就没接🤣

😆，祝好～

**Comment by Qing-Novel** [comment]
> > > 或许可以问问别的大佬。
> > 
> > 
> > 问过一位了，那位不用就没接🤣
> 
> 😆，祝好～

🤣
