### ISSUE TITLE
状态栏图标反色异常问题

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#25]
跟状态栏颜色一样看不清图标了，也是打开关于就恢复了

https://github.com/user-attachments/assets/062e05b0-8dba-4070-9f64-3639624e195d

**Comment by Qing-Novel** [comment]
使用的版本是第16个版本

**Comment by qixiaoo** [comment]
确实，后面有时间了我看看，最近摸了

**Comment by Qing-Novel** [comment]
> 确实，后面有时间了我看看，最近摸了

行，坐等佬更新，这个问题佬可以参考这个
https://github.com/Predidit/Kazumi/issues/240

**Comment by qixiaoo** [comment]
已修复
