### ISSUE TITLE
关于付费章节的显示问题

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#4]
在付费章节购买前是空白的（网页上是有内容的），购买了才能显示内容，希望大佬可以做下适配

https://github.com/user-attachments/assets/44cd2db9-0d4b-4e14-95d0-b49f6b0f5068

**Comment by qixiaoo** [comment]
我会看看网页端是怎么购买的，预计后面会加上购买的功能。

**Comment by Qing-Novel** [comment]
> 我会看看网页端是怎么购买的，预计后面会加上购买的功能。

好的大佬

**Comment by qixiaoo** [comment]
已实现
