### ISSUE TITLE
跟原版网页相比多出来的章节问题

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#7]
无意间发现app里多了一个网页上没有的章节，点开也没内容是空白的，随附录屏，麻烦大佬看看啥情况。
ps：发现收藏的部分小说和部分章节（之前提到的付费解锁的章节和这次反馈的章节）都有一个标志，不知道那个标志是干什么用的

https://github.com/user-attachments/assets/5d6407ed-a2dc-49d6-9fac-5d879ddc2c30

**Comment by qixiaoo** [comment]
看了一下，原始数据里确实有“报错楼”这么一个数据。
看起来像是网页端在展示时，对等级不够的用户隐藏了（等级 6 才能访问）。

以及小说和章节右侧的叹号意味着小说和章节设置了等级或者付费限制，长按可以看到提示。

**Comment by Qing-Novel** [comment]
> 看了一下，原始数据里确实有“报错楼”这么一个数据。 看起来像是网页端在展示时，对等级不够的用户隐藏了（等级 6 才能访问）。
> 
> 以及小说和章节右侧的叹号意味着小说和章节设置了等级或者付费限制，长按可以看到提示。

我用我大号看了下真的是啊XD好家伙，长按可以看吗。。。之前一直是点击

**Comment by Qing-Novel** [comment]
佬，这个issue也可以关了

**Comment by Qing-Novel** [comment]
佬，这个issue您这边可以关了
