### ISSUE TITLE
关于界面动画的建议

### ISSUE THREAD

**Issue by Qing-Novel** [qixiaoo/masiro#9]
看到佬更新了个人主页和签到功能很是开心，离app的完全体更近了一步，小提一个建议，就是切换界面的动画个人感觉有点问题，感觉不太舒服，看起来是当前界面变透明然后消失同时底层出现新界面然后显示，这就导致会有上个界面的内容残留了，不知道大佬后续有没有计划调整下这部分呢？（也不是bug，这么放着也没啥大毛病）

https://github.com/user-attachments/assets/772b6b0c-7656-4290-a9fd-533bcb4fb664

**Comment by qixiaoo** [comment]
像是子路由过渡动画有问题。
尝试修复了一版，切换时透明的问题算是解决了。

**Comment by Qing-Novel** [comment]
> 像是子路由过渡动画有问题。 尝试修复了一版，切换时透明的问题算是解决了。

好的好的，幸苦大佬了

**Comment by qixiaoo** [comment]
已修复
